package com.grupofarmacos.hcmc.ap005.model.am.common;

import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 26 10:21:02 CDT 2017
// ---------------------------------------------------------------------
public interface AP005AM extends ApplicationModule {
    Boolean insertPayload(String payload, String estatus, String dateTime);

    Boolean insertEmploy();

    Map getProperties(String criterial);

    Boolean garantizarAcceso(String user);
}
