package com.grupofarmacos.hcmc.ap005.model.vo;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 17 19:23:17 CDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeTableVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EmployeNumberPsoft {
            public Object get(EmployeeTableVORowImpl obj) {
                return obj.getEmployeNumberPsoft();
            }

            public void put(EmployeeTableVORowImpl obj, Object value) {
                obj.setEmployeNumberPsoft((String)value);
            }
        }
        ,
        VendorName {
            public Object get(EmployeeTableVORowImpl obj) {
                return obj.getVendorName();
            }

            public void put(EmployeeTableVORowImpl obj, Object value) {
                obj.setVendorName((String)value);
            }
        }
        ,
        EffectiveStartDate {
            public Object get(EmployeeTableVORowImpl obj) {
                return obj.getEffectiveStartDate();
            }

            public void put(EmployeeTableVORowImpl obj, Object value) {
                obj.setEffectiveStartDate((String)value);
            }
        }
        ,
        ActiveUser {
            public Object get(EmployeeTableVORowImpl obj) {
                return obj.getActiveUser();
            }

            public void put(EmployeeTableVORowImpl obj, Object value) {
                obj.setActiveUser((String)value);
            }
        }
        ,
        TypeUser {
            public Object get(EmployeeTableVORowImpl obj) {
                return obj.getTypeUser();
            }

            public void put(EmployeeTableVORowImpl obj, Object value) {
                obj.setTypeUser((String)value);
            }
        }
        ,
        Accion {
            public Object get(EmployeeTableVORowImpl obj) {
                return obj.getAccion();
            }

            public void put(EmployeeTableVORowImpl obj, Object value) {
                obj.setAccion((String)value);
            }
        }
        ,
        EffectiveDate_AP005 {
            public Object get(EmployeeTableVORowImpl obj) {
                return obj.getEffectiveDate_AP005();
            }

            public void put(EmployeeTableVORowImpl obj, Object value) {
                obj.setEffectiveDate_AP005((String)value);
            }
        }
        ,
        EffectiveSequence_AP005 {
            public Object get(EmployeeTableVORowImpl obj) {
                return obj.getEffectiveSequence_AP005();
            }

            public void put(EmployeeTableVORowImpl obj, Object value) {
                obj.setEffectiveSequence_AP005((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(EmployeeTableVORowImpl object);

        public abstract void put(EmployeeTableVORowImpl object, Object value);

        public int index() {
            return EmployeeTableVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return EmployeeTableVORowImpl.AttributesEnum.firstIndex() + EmployeeTableVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = EmployeeTableVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int EMPLOYENUMBERPSOFT = EmployeeTableVORowImpl.AttributesEnum.EmployeNumberPsoft.index();
    public static final int VENDORNAME = EmployeeTableVORowImpl.AttributesEnum.VendorName.index();
    public static final int EFFECTIVESTARTDATE = EmployeeTableVORowImpl.AttributesEnum.EffectiveStartDate.index();
    public static final int ACTIVEUSER = EmployeeTableVORowImpl.AttributesEnum.ActiveUser.index();
    public static final int TYPEUSER = EmployeeTableVORowImpl.AttributesEnum.TypeUser.index();
    public static final int ACCION = EmployeeTableVORowImpl.AttributesEnum.Accion.index();
    public static final int EFFECTIVEDATE_AP005 = EmployeeTableVORowImpl.AttributesEnum.EffectiveDate_AP005.index();
    public static final int EFFECTIVESEQUENCE_AP005 = EmployeeTableVORowImpl.AttributesEnum.EffectiveSequence_AP005.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeTableVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute EmployeNumberPsoft.
     * @return the EmployeNumberPsoft
     */
    public String getEmployeNumberPsoft() {
        return (String) getAttributeInternal(EMPLOYENUMBERPSOFT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmployeNumberPsoft.
     * @param value value to set the  EmployeNumberPsoft
     */
    public void setEmployeNumberPsoft(String value) {
        setAttributeInternal(EMPLOYENUMBERPSOFT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VendorName.
     * @return the VendorName
     */
    public String getVendorName() {
        return (String) getAttributeInternal(VENDORNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VendorName.
     * @param value value to set the  VendorName
     */
    public void setVendorName(String value) {
        setAttributeInternal(VENDORNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EffectiveStartDate.
     * @return the EffectiveStartDate
     */
    public String getEffectiveStartDate() {
        return (String) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EffectiveStartDate.
     * @param value value to set the  EffectiveStartDate
     */
    public void setEffectiveStartDate(String value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActiveUser.
     * @return the ActiveUser
     */
    public String getActiveUser() {
        return (String) getAttributeInternal(ACTIVEUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActiveUser.
     * @param value value to set the  ActiveUser
     */
    public void setActiveUser(String value) {
        setAttributeInternal(ACTIVEUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TypeUser.
     * @return the TypeUser
     */
    public String getTypeUser() {
        return (String) getAttributeInternal(TYPEUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TypeUser.
     * @param value value to set the  TypeUser
     */
    public void setTypeUser(String value) {
        setAttributeInternal(TYPEUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Accion.
     * @return the Accion
     */
    public String getAccion() {
        return (String) getAttributeInternal(ACCION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Accion.
     * @param value value to set the  Accion
     */
    public void setAccion(String value) {
        setAttributeInternal(ACCION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EffectiveDate_AP005.
     * @return the EffectiveDate_AP005
     */
    public String getEffectiveDate_AP005() {
        return (String) getAttributeInternal(EFFECTIVEDATE_AP005);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EffectiveDate_AP005.
     * @param value value to set the  EffectiveDate_AP005
     */
    public void setEffectiveDate_AP005(String value) {
        setAttributeInternal(EFFECTIVEDATE_AP005, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EffectiveSequence_AP005.
     * @return the EffectiveSequence_AP005
     */
    public String getEffectiveSequence_AP005() {
        return (String) getAttributeInternal(EFFECTIVESEQUENCE_AP005);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EffectiveSequence_AP005.
     * @param value value to set the  EffectiveSequence_AP005
     */
    public void setEffectiveSequence_AP005(String value) {
        setAttributeInternal(EFFECTIVESEQUENCE_AP005, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= EmployeeTableVORowImpl.AttributesEnum.firstIndex()) && (index < EmployeeTableVORowImpl.AttributesEnum.count())) {
            return EmployeeTableVORowImpl.AttributesEnum.staticValues()[index - EmployeeTableVORowImpl.AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= EmployeeTableVORowImpl.AttributesEnum.firstIndex()) && (index < EmployeeTableVORowImpl.AttributesEnum.count())) {
            EmployeeTableVORowImpl.AttributesEnum.staticValues()[index - EmployeeTableVORowImpl.AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
