package com.grupofarmacos.hcmc.ap005.model.am.client;

import com.grupofarmacos.hcmc.ap005.model.am.common.AP005AM;

import java.util.Map;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 26 10:21:02 CDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AP005AMClient extends ApplicationModuleImpl implements AP005AM {
    /**
     * This is the default constructor (do not remove).
     */
    public AP005AMClient() {
    }


    public Boolean insertPayload(String payload, String estatus,
                                 String dateTime) {
        Object _ret =
            this.riInvokeExportedMethod(this,"insertPayload",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {payload, estatus, dateTime});
        return (Boolean)_ret;
    }

    public Boolean insertEmploy() {
        Object _ret = this.riInvokeExportedMethod(this,"insertEmploy",null,null);
        return (Boolean)_ret;
    }

    public Map getProperties(String criterial) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getProperties",new String [] {"java.lang.String"},new Object[] {criterial});
        return (Map)_ret;
    }

    public Boolean garantizarAcceso(String user) {
        Object _ret =
            this.riInvokeExportedMethod(this,"garantizarAcceso",new String [] {"java.lang.String"},new Object[] {user});
        return (Boolean)_ret;
    }
}
